# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtmain_3.ui'
#
# Created: Wed Nov 23 17:19:18 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setToolTip("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.run = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run.sizePolicy().hasHeightForWidth())
        self.run.setSizePolicy(sizePolicy)
        self.run.setObjectName("run")
        self.gridLayout = QtGui.QGridLayout(self.run)
        self.gridLayout.setObjectName("gridLayout")
        self.horizSplitter = QtGui.QSplitter(self.run)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizSplitter.sizePolicy().hasHeightForWidth())
        self.horizSplitter.setSizePolicy(sizePolicy)
        self.horizSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.horizSplitter.setChildrenCollapsible(False)
        self.horizSplitter.setObjectName("horizSplitter")
        self.layoutWidget = QtGui.QWidget(self.horizSplitter)
        self.layoutWidget.setMaximumSize(QtCore.QSize(600, 16777215))
        self.layoutWidget.setObjectName("layoutWidget")
        self.left_VertLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.left_VertLayout.setContentsMargins(0, 0, 0, 0)
        self.left_VertLayout.setObjectName("left_VertLayout")
        self.progress_HorizLayout = QtGui.QHBoxLayout()
        self.progress_HorizLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.progress_HorizLayout.setObjectName("progress_HorizLayout")
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(600, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.progress_HorizLayout.addWidget(self.progressBar)
        self.stopButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 20))
        self.stopButton.setMaximumSize(QtCore.QSize(600, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 157, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 174, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.stopButton.setPalette(palette)
        self.stopButton.setAutoFillBackground(False)
        self.stopButton.setDefault(False)
        self.stopButton.setFlat(False)
        self.stopButton.setObjectName("stopButton")
        self.progress_HorizLayout.addWidget(self.stopButton)
        self.progress_HorizLayout.setStretch(0, 1)
        self.left_VertLayout.addLayout(self.progress_HorizLayout)
        self.totalresults_text = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalresults_text.sizePolicy().hasHeightForWidth())
        self.totalresults_text.setSizePolicy(sizePolicy)
        self.totalresults_text.setMinimumSize(QtCore.QSize(407, 47))
        self.totalresults_text.setMaximumSize(QtCore.QSize(600, 47))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.totalresults_text.setFont(font)
        self.totalresults_text.setAutoFillBackground(False)
        self.totalresults_text.setFrameShape(QtGui.QFrame.StyledPanel)
        self.totalresults_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.totalresults_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.totalresults_text.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.totalresults_text.setAcceptRichText(True)
        self.totalresults_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.totalresults_text.setOpenLinks(False)
        self.totalresults_text.setObjectName("totalresults_text")
        self.left_VertLayout.addWidget(self.totalresults_text)
        self.testTable = QtGui.QTableWidget(self.layoutWidget)
        self.testTable.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTable.sizePolicy().hasHeightForWidth())
        self.testTable.setSizePolicy(sizePolicy)
        self.testTable.setMinimumSize(QtCore.QSize(200, 100))
        self.testTable.setMaximumSize(QtCore.QSize(600, 16777215))
        self.testTable.setBaseSize(QtCore.QSize(0, 0))
        self.testTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.testTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.testTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.testTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.testTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.testTable.setRowCount(0)
        self.testTable.setObjectName("testTable")
        self.testTable.setColumnCount(4)
        self.testTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(3, item)
        self.testTable.horizontalHeader().setCascadingSectionResizes(False)
        self.testTable.horizontalHeader().setDefaultSectionSize(100)
        self.testTable.horizontalHeader().setMinimumSectionSize(25)
        self.testTable.horizontalHeader().setStretchLastSection(True)
        self.testTable.verticalHeader().setDefaultSectionSize(21)
        self.left_VertLayout.addWidget(self.testTable)
        self.left_VertLayout.setStretch(2, 1)
        self.layoutWidget1 = QtGui.QWidget(self.horizSplitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.right_VertLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.right_VertLayout.setContentsMargins(0, 0, 0, 0)
        self.right_VertLayout.setObjectName("right_VertLayout")
        self.right_VertLayout_2 = QtGui.QVBoxLayout()
        self.right_VertLayout_2.setObjectName("right_VertLayout_2")
        self.barcode_HorizLayout = QtGui.QHBoxLayout()
        self.barcode_HorizLayout.setObjectName("barcode_HorizLayout")
        self.barcodeLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barcodeLineEdit.sizePolicy().hasHeightForWidth())
        self.barcodeLineEdit.setSizePolicy(sizePolicy)
        self.barcodeLineEdit.setMinimumSize(QtCore.QSize(0, 10))
        self.barcodeLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.barcodeLineEdit.setObjectName("barcodeLineEdit")
        self.barcode_HorizLayout.addWidget(self.barcodeLineEdit)
        spacerItem = QtGui.QSpacerItem(40, 13, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.barcode_HorizLayout.addItem(spacerItem)
        self.testButton = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testButton.sizePolicy().hasHeightForWidth())
        self.testButton.setSizePolicy(sizePolicy)
        self.testButton.setMinimumSize(QtCore.QSize(100, 20))
        self.testButton.setObjectName("testButton")
        self.barcode_HorizLayout.addWidget(self.testButton)
        self.right_VertLayout_2.addLayout(self.barcode_HorizLayout)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(550, 200))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setObjectName("graphicsView")
        self.right_VertLayout_2.addWidget(self.graphicsView)
        self.right_VertLayout.addLayout(self.right_VertLayout_2)
        self.label = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.right_VertLayout.addWidget(self.label)
        self.testLogTable = QtGui.QListWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testLogTable.sizePolicy().hasHeightForWidth())
        self.testLogTable.setSizePolicy(sizePolicy)
        self.testLogTable.setMinimumSize(QtCore.QSize(0, 200))
        self.testLogTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        self.testLogTable.setFont(font)
        self.testLogTable.setProperty("isWrapping", False)
        self.testLogTable.setResizeMode(QtGui.QListView.Adjust)
        self.testLogTable.setObjectName("testLogTable")
        self.right_VertLayout.addWidget(self.testLogTable)
        self.right_VertLayout.setStretch(0, 1)
        self.gridLayout.addWidget(self.horizSplitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.run, "")
        self.details = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details.sizePolicy().hasHeightForWidth())
        self.details.setSizePolicy(sizePolicy)
        self.details.setObjectName("details")
        self.gridLayout_4 = QtGui.QGridLayout(self.details)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.details_gridLayout = QtGui.QGridLayout()
        self.details_gridLayout.setObjectName("details_gridLayout")
        self.bottom_HorizLayout = QtGui.QHBoxLayout()
        self.bottom_HorizLayout.setObjectName("bottom_HorizLayout")
        self.limitToLabel = QtGui.QLabel(self.details)
        self.limitToLabel.setObjectName("limitToLabel")
        self.bottom_HorizLayout.addWidget(self.limitToLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom_HorizLayout.addItem(spacerItem1)
        self.dbsyncPushButton = QtGui.QPushButton(self.details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbsyncPushButton.sizePolicy().hasHeightForWidth())
        self.dbsyncPushButton.setSizePolicy(sizePolicy)
        self.dbsyncPushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dbsyncPushButton.setObjectName("dbsyncPushButton")
        self.bottom_HorizLayout.addWidget(self.dbsyncPushButton)
        self.details_gridLayout.addLayout(self.bottom_HorizLayout, 1, 0, 1, 1)
        self.dbresultsTableWidget = QtGui.QTableWidget(self.details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbresultsTableWidget.sizePolicy().hasHeightForWidth())
        self.dbresultsTableWidget.setSizePolicy(sizePolicy)
        self.dbresultsTableWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dbresultsTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.dbresultsTableWidget.setProperty("showDropIndicator", True)
        self.dbresultsTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.dbresultsTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dbresultsTableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.dbresultsTableWidget.setObjectName("dbresultsTableWidget")
        self.dbresultsTableWidget.setColumnCount(4)
        self.dbresultsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.dbresultsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dbresultsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dbresultsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dbresultsTableWidget.setHorizontalHeaderItem(3, item)
        self.dbresultsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.dbresultsTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.dbresultsTableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.dbresultsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.dbresultsTableWidget.verticalHeader().setDefaultSectionSize(21)
        self.dbresultsTableWidget.verticalHeader().setSortIndicatorShown(True)
        self.details_gridLayout.addWidget(self.dbresultsTableWidget, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.details_gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.details, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Board Test Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.testTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.testTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.testTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.testTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Expected", None, QtGui.QApplication.UnicodeUTF8))
        self.barcodeLineEdit.setText(QtGui.QApplication.translate("MainWindow", "barcode", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("MainWindow", "TEST", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Log Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.run), QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.limitToLabel.setText(QtGui.QApplication.translate("MainWindow", "Results limited to [XX] last records from DB", None, QtGui.QApplication.UnicodeUTF8))
        self.dbsyncPushButton.setText(QtGui.QApplication.translate("MainWindow", "Sync DB", None, QtGui.QApplication.UnicodeUTF8))
        self.dbresultsTableWidget.setSortingEnabled(True)
        self.dbresultsTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Barcode", None, QtGui.QApplication.UnicodeUTF8))
        self.dbresultsTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dbresultsTableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.dbresultsTableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.details), QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))

